### ISSUE TITLE
[Backend] Authentication & Role

### ISSUE THREAD

**Issue by SebGrd** [waliidhakim/challenge_flutter_go#4]
# Authentication & Role on the backend
Add the authentication system for the Users and add the role feature so some routes are protected by privileges.
## Todo

- [ ] Search for Authentication system in Go (JWT, Token, ...)
- [ ] Hash the password on account creation/password modification
- [ ] Handle user role on account creation
- [ ] Handle middleware for protected routes

## Scope
- Go
  - User model
  - All routes that need role protection
